language: java
sudo: false
install: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
dist: trusty

addons:
  sonarcloud:
    organization: "latte"
    token:
      secure: "qa/Mr9Roo51KLM7q1SsaxUCXnvX59BfMqx7WrqHIDFrdw2CT8sj4wGj5G9AEBqgaRoL/D+xHUGG1puUxtPiTc5QAGMh87PdmdgvHaB/rfpu8YjBbmnexI5GK8pJ1SUw+Yxdn1Pq3S1y6W0Gi88PZBjihxsFEE1N9r03HIOMLBEeUok0Dw953RVy6TYD4VGkpYZoW6u3VBX7q8W7FHP7vIy/gS25j/c9g4mUUWU9kvCBE8tmV/A05ex9QBPPzDjIkOjhrfNdCZLKPFM0j9QT99OBFo5cUMrRVFnLRh3fFfkvsQfGFbpP+T3lL9G5cJw6pvDR62cNBgg0uu2rULtcz6JIVwFz2ekuj+PmpcIpD2EEAOZ+nRGCSocJsMHSO3usq6PLOFSWQF22AyxgaalCbfhtEC7GQ4+W9722v3Im4uiHZsLr0G7eCCqdBxrqHKc75jjB7u2tutnB+RYQ20UM/qrv+f3i83zsjTe0iraxgCPR7HZBplooUWdSeVyB7xrAREl2rXqiwXmpYUzXMqBifPxW71ZbYs3mOO8qOKiT1ARc6ljykKwC0pfppgBjbQf12leXxo72XdU/aK7+O0wjfGenEXmYkA28Y8m+tgUaRyaZwYqDbEpzcL7L+SY7e2ULrcNxrGWgRley1f2Bs7LVY0ayjV2UBDPyu9gywutfzIqk="

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

deploy:
  provider: releases
  api_key:
    secure: "dhfdJ47LpU70Dly44acQ4nlYyGW1oNGyfgpE/Lb5wjvNIMGWvBoZ0ZGppQUiWGonJ7APcSQIFWy3jdMfgiE6fAKf5YfyoZgcmY5/wjuYIpHfsk2PzuLSCx5BgHKyUFQLeQejimWfzE9DEM8hA32ehKUpsqbcVlkprKdnvy1WtB8aVBLK2JRN5hDL/R3cT2RvzhDN+uAuQOmPWrfRjj86ZkknRj4NN+yUIACs7WDsvemY/5bCflp7/qe1/cv+6pzR8l/loim4FK1aFu800N9ZzT4anCzVkiYIyD4Pjc2v8YJs8XBC+BQRj/eij4qkxQ/yzofdaB9XSBKVgh0BZeaznFgakQqYOunWa3A4GuKGA1Hz0efGVYzmrdHTMHMhZb39o/8cLbqlOlSGp6TwZseOtCAuJXn4Z7F9yy8hS1z+HRQX+6wwb5B6R/Obh8lJ1ZQksq6svKa87Ga/dtjrrYUdrCe4gF6b4Qh88HjnVh82KtwLFT7VoU1iSptw0idvyzskyPfz0G1e7Wxylr4dywxOy9ltA6jfOyTUsRZ3CtgX+QeMjhUurMNPnTLHxJqht5erItQnEMi67CeUPxSiuFvgmO3y937TWwXpHMPTao34nWgW4FTQdnfWJiNn7snEWXkNYutdeEbQeszAYcH4NV8kLiiad4zM1DBGC3oIewAd7/Q="
  file: build/libs/latte.jar
  on:
    repo: LatteLang/Latte
    tags: true
