language: java
sudo: false
install: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
dist: trusty

addons:
  sonarcloud:
    organization: "ranolp-github"
    token:
      secure: "qa/Mr9Roo51KLM7q1SsaxUCXnvX59BfMqx7WrqHIDFrdw2CT8sj4wGj5G9AEBqgaRoL/D+xHUGG1puUxtPiTc5QAGMh87PdmdgvHaB/rfpu8YjBbmnexI5GK8pJ1SUw+Yxdn1Pq3S1y6W0Gi88PZBjihxsFEE1N9r03HIOMLBEeUok0Dw953RVy6TYD4VGkpYZoW6u3VBX7q8W7FHP7vIy/gS25j/c9g4mUUWU9kvCBE8tmV/A05ex9QBPPzDjIkOjhrfNdCZLKPFM0j9QT99OBFo5cUMrRVFnLRh3fFfkvsQfGFbpP+T3lL9G5cJw6pvDR62cNBgg0uu2rULtcz6JIVwFz2ekuj+PmpcIpD2EEAOZ+nRGCSocJsMHSO3usq6PLOFSWQF22AyxgaalCbfhtEC7GQ4+W9722v3Im4uiHZsLr0G7eCCqdBxrqHKc75jjB7u2tutnB+RYQ20UM/qrv+f3i83zsjTe0iraxgCPR7HZBplooUWdSeVyB7xrAREl2rXqiwXmpYUzXMqBifPxW71ZbYs3mOO8qOKiT1ARc6ljykKwC0pfppgBjbQf12leXxo72XdU/aK7+O0wjfGenEXmYkA28Y8m+tgUaRyaZwYqDbEpzcL7L+SY7e2ULrcNxrGWgRley1f2Bs7LVY0ayjV2UBDPyu9gywutfzIqk="

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

deploy:
  provider: releases
  api_key:
    secure: S0LJDJ++oCPYv3T9WI1DRRpncu5Mf2eN7mntuVWT91HXlkughqliMdKey4bTPgNbRnWtrIoq6doXa8+bfT+fwC5C9CjntzhWo+PsCNzXP3HbuqAyd0teX2e3QknZocYgSvFMO1onqxfYkRt5/YlUmHJzofJJuU+IsGPUA6oa7cxJYvGik107Z/c56XUlxV3TXePDR0XKWRSHK4FeuknaNainIeHWmQ3oVqX+77Q8zeFRNdnB8oAQe+p0tTj3DkJwYpGKwCtsXrTwPEDy6HduARFtQmxg2ZSixw8/bluOmChO1exkqxhjTJeK4L9boxfzO/bG4gp3J6ZLG/N0R6cQOXt5FbCMaWHL/4TD3Zq3aL5HDucl4wgL2nma7pedivvUMSrTyfAc1zNLEtVH7fVjeOVtXFXzRmZfAQqSUxLCeDJiWjIBITmTWkN+P6LCFm/Dj0W7ScMfgHmx2c1q7v+eDYYhI8iSRM3xuonpHogxc4Oxm/7UxLD8J192FijRYI9iYHQdg7ALRgsKolA9Py8LxDyMVqicUABtj6xtQqDobkJ+JSHNZR7MF8OFocHFChR++c8y9RRjoqnQuLPSlamIBlrDlW9Qqs4l/QJccJTP/R9Xvk2qlBgW88K2/oJeQn7CErRoeLdrCm1xg4C2ws14aNR+awikmKyvTQbNO/+fd/w=
  file: build/libs/latte.jar
  on:
    repo: LatteLang/Latte
    tags: true
